name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  pull-requests: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: mcp-insomnia
      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@latest
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm audit
        if: ${{ steps.release.outputs.release_created }}
      - run: npm run lint
        if: ${{ steps.release.outputs.release_created }}
      - run: npm run lint:eslint
        if: ${{ steps.release.outputs.release_created }}
      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish --provenance
        if: ${{ steps.release.outputs.release_created }}
